// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using project.Models.ProductModels.Domain;


#nullable disable

namespace project.Migrations.MyDb
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230412050454_ISAPROVEDPRODUCT")]
    partial class ISAPROVEDPRODUCT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("project.Models.ShoppingCartModels.Domain.Product", b =>
                {
                    b.Property<int>("PrdoductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrdoductId"), 1L, 1);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isAproved")
                        .HasColumnType("bit");

                    b.Property<string>("vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrdoductId");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
